#!/bin/sh

cd $HOME
git clone https://github.com/dcreager/dotfiles-base .dotfiles.base
git clone https://github.com/dcreager/dotfiles-public -b linux .dotfiles.public
$HOME/.dotfiles.base/bin/dotfiles.symlink install
